---
functional:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт дожен вести учет посещаемости, отмечать пиковые нагрузки
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен при регистрации отправлять электронное письмо для пользователя
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен иметь языковые локалии на множестве языков
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть интуитивно понятным для малоопытных пользователей
  
